export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'

export const FETCH_FOLLOWERS_REQUEST = 'FEATURED_FOLLOWERS_REQUEST';

export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';

export const FETCH_FOLLOWERS_FAILURE = 'FETCH_FOLLOWERS_FAILURE';

export const FETCH_FOLLOWER_REPOSITORIES_SUCCESS = 'FETCH_FOLLOWER_REPOSITORIES_SUCCESS';